### ISSUE TITLE
IOS 11.2.1 界面切换一闪一闪

### ISSUE THREAD

**Issue by hooliy** [growu/drip-ionic3#1]
如题！

**Comment by jasonz1987** [comment]
@hooliy 稍候我测试一下～

**Comment by jasonz1987** [comment]
@hooliy 我几台ios设备上测试好像都没问题，能否录个视频或者做个gif看下，我的微信：foxmee

**Comment by hooliy** [comment]
@jasonz1987 系统自动更新了，IOS 11.2.2上没发现！

**Comment by jasonz1987** [comment]
@hooliy OK 多谢反馈 那再观察观察。

**Comment by songjian931798** [comment]
兄dei,那个imagepicker这样写，在ios上选择相册图片不会出问题吗？

**Comment by jasonz1987** [comment]
@songjian931798 具体指的是哪块代码呢，目前IOS上选择图片是正常的。
