### ISSUE TITLE
求问大神关于在http请求错误处理时路由跳转的问题

### ISSUE THREAD

**Issue by xiguashiwode** [growu/drip-ionic3#2]
this.app.getRootNav().push('login');
在我自己的http-service里面，
我已经引入了App,也定义app了，但是上面这句代码写进去却没有任何反应，不知道还需要在哪加什么条件吗？请大神指导一下

**Comment by jasonz1987** [comment]
请把全部代码贴上来把。

**Comment by xiguashiwode** [comment]
`import { Injectable } from "@angular/core";
import { Http, Response, Headers, RequestOptions } from "@angular/http";
import { App } from "ionic-angular";
import "rxjs/add/operator/map";
import "rxjs/add/operator/toPromise";
/**
 * HTTP请求服务
 */
@Injectable()
export class HttpSerProvider {
  constructor(public http: Http, private app: App) {
    // console.log('Hello HttpSerProvider Provider');
  }

  /**
   * get方式请求
   * @param {string} url     //url
   * @param paramObj      //json对象 如:{name:'大见',age:'23'}
   * @return {Promise<never | {}>}
   */
  get(url: string, paramObj: any = {}) {
    let timestamp = Math.floor(
      new Date().getTime() / 1000 - 1420070400
    ).toString(); //获取当前时间 减 2015年1月1日的 时间戳
    let headers = new Headers({ timestamp: timestamp });
    let options = new RequestOptions({ headers: headers });
    return this.http
      .get(url + this.toQueryString(paramObj), options)
      .toPromise()
      .then(this.extractData)
      .catch(this.handleError);
  }

  /**
   * post方式请求
   * @param {string} url
   * @param body       //如：paramObj:{name:'大见',age:'23'}
   * @param {string} contentType      //post请求的编码方式  application/x-www-form-urlencoded  multipart/form-data   application/json   text/xml
   * @return {Promise<never | {}>}
   */
  post(
    url: string,
    body: any = {},
    contentType: string = "application/json;charset=UTF-8"
  ) {
    let headers = new Headers({
      "Content-Type": contentType,
      buId: "apptest01",
      uuId: "apptest01",
      deviceId: "9qu094u3r019u",
      app_version: "1.0.0",
      appId: "111111",
      Authorization:
        url.indexOf("login") == -1
          ? "Bearer" + localStorage.getItem("token")
          : "Basic QVBQU1RPUkVfQ2xpZW50OnBhc3N3MHJk"
    });
    let options = new RequestOptions({ headers: headers });
    return this.http
      .post(url, body, options)
      .toPromise()
      .then(this.extractData)
      .catch(this.handleError);
  }

  
  private handleError(error: Response | any) {
    let errMsg: string;
    if (error instanceof Response) {
      const body = error.json() || "";
      const err = body.error || JSON.stringify(body);
      errMsg = `${error.status} - ${error.statusText || ""} ${err}`;
      if (`${error.status}` == "401") {
        this.app.getRootNav().push("login");
      }
    } else {
      errMsg = error.message ? error.message : error.toString();
    }
    return Promise.reject(errMsg);
  }
}`

**Comment by jasonz1987** [comment]
@xiguashiwode 代码写的没有问题 ，确定执行到这一步了吗。 然后打印一下this.app.getRootNav() 是否有值，没有值得话 发一下调用这个方法的代码。

**Comment by xiguashiwode** [comment]
执行了的，我使用alert（1）可以弹出对话框，使用console.log的时候，连续三个console.log:
console.log(1);
console.log(this.app.getRootNav());
console.log（2）;
这样只能打印出1，接下来两个都不打印，然后就结束了，也没有报错，方便的话加个微信，谢谢
